name: lambda-gha
description: GitHub Action for creating a self-hosted runner on Lambda Labs GPU cloud.
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  action_ref:
    description: "lambda-gha Git ref (branch/tag/SHA) to use for fetching scripts"
    required: false
    default: "main"
  debug:
    description: "Debug mode: false=off, true/trace=set -x only, number=set -x + sleep N minutes before shutdown"
    required: false
  extra_gh_labels:
    description: "Extra GitHub labels for the runner (comma-separated, no spaces)"
    required: false
  instance_count:
    description: "Number of instances to create (default: 1)"
    required: false
    default: "1"
  instance_type:
    description: "Lambda instance type (e.g., gpu_1x_a10, gpu_8x_a100_80gb_sxm4)"
    required: false
  lambda_api_key:
    description: "Lambda Labs API key (falls back to secrets.LAMBDA_API_KEY)"
    required: false
  max_instance_lifetime:
    description: "Maximum instance lifetime in minutes before shutdown (default: 360)"
    required: false
  region:
    description: "Lambda region (e.g., us-south-1, us-west-1)"
    required: false
  repo:
    description: "GitHub repo to register runner with (default: current repo)"
    required: false
  runner_grace_period:
    description: "Seconds before terminating after last job completes (default: 60)"
    required: false
  runner_initial_grace_period:
    description: "Seconds before terminating if no jobs start (default: 180)"
    required: false
  runner_poll_interval:
    description: "Seconds between termination condition checks (default: 10)"
    required: false
  runner_registration_timeout:
    description: "Max seconds to wait for runner registration (default: 300)"
    required: false
  ssh_key_names:
    description: "SSH key names registered in Lambda Labs (comma-separated)"
    required: false
  userdata:
    description: "Additional script to run before runner setup"
    required: false
outputs:
  mtx:
    description: "JSON array for matrix strategies: [{idx, id (label), instance_id}, ...]"
  label:
    description: "Runner label (for single instance use)"
  instance-id:
    description: "Lambda instance ID (for single instance use)"
