name: ec2-gha
description: GitHub Action for creating a self-hosted runner on AWS.
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  action_ref:
    description: "ec2-gha Git ref (branch/tag/SHA) to use for fetching scripts"
    required: false
    default: "v2"
  aws_region:
    description: "AWS region for EC2 instances (falls back to vars.AWS_REGION, then us-east-1)"
    required: false
  aws_subnet_id:
    description: "AWS subnet ID (will use the account default subnet if not specified)"
    required: false
  aws_tags:
    description: "AWS tags to apply to EC2 instances (JSON array format)"
    required: false
  cloudwatch_logs_group:
    description: "CloudWatch Logs group name for streaming runner logs (leave empty to disable)"
    required: false
  debug:
    description: "Debug mode: false=off, true/trace=set -x only, number=set -x + sleep N minutes before shutdown"
    required: false
  ec2_home_dir:
    description: "Home directory on the AWS instance (falls back to vars.EC2_HOME_DIR, then auto-detection)"
    required: false
  ec2_image_id:
    description: "AWS AMI ID to use (required - must be provided via input or vars.EC2_IMAGE_ID)"
    required: false
  ec2_instance_profile:
    description: "Instance profile name to attach to launched EC2 instance (required for CloudWatch logging)"
    required: false
  ec2_instance_type:
    description: "AWS instance type (falls back to vars.EC2_INSTANCE_TYPE, then t3.medium)"
    required: false
  ec2_key_name:
    description: "Name of an EC2 key pair to use for SSH access (falls back to vars.EC2_KEY_NAME)"
    required: false
  ec2_root_device_size:
    description: "Root disk size in GB (0=AMI default, +N=AMI+N GB for testing, e.g. +2)"
    required: false
  ec2_security_group_id:
    description: "AWS security group ID (falls back to vars.EC2_SECURITY_GROUP_ID)"
    required: false
  ec2_userdata:
    description: "Additional userdata script to run on instance startup (before runner starts)"
    required: false
  extra_gh_labels:
    description: "Any extra GitHub labels to tag your runners with. Passed as a comma-separated list with no spaces"
    required: false
  instance_count:
    description: "The number of instances to create, defaults to 1"
    required: false
    default: "1"
  instance_name:
    description: "Name tag template for EC2 instances. Uses Python string.Template format with variables: $repo, $name (workflow filename stem), $workflow (full workflow name), $ref, $run (number), $idx (0-based instance index for multi-instance launches). Default: $repo/$name#$run (or $repo/$name#$run $idx for multi-instance)"
    required: false
  max_instance_lifetime:
    description: "Maximum instance lifetime in minutes before automatic shutdown (default 360 = 6 hours)"
    required: false
  repo:
    description: "The repo to run against. Will use the current repo if not specified."
    required: false
  runner_grace_period:
    description: "Grace period in seconds before terminating instance after last job completes (falls back to vars.RUNNER_GRACE_PERIOD, then 60)"
    required: false
  runner_initial_grace_period:
    description: "Grace period in seconds before terminating instance if no jobs start (falls back to vars.RUNNER_INITIAL_GRACE_PERIOD, then 180)"
    required: false
  runner_poll_interval:
    description: "How often (in seconds) to check termination conditions (falls back to vars.RUNNER_POLL_INTERVAL, then 10)"
    required: false
  runner_registration_timeout:
    description: "Maximum seconds to wait for runner to register with GitHub (falls back to vars.RUNNER_REGISTRATION_TIMEOUT, then 360 = 6 minutes)"
    required: false
  runners_per_instance:
    description: "Number of runners to register per instance (each in separate directories to allow concurrent jobs)"
    required: false
    default: "1"
  ssh_pubkey:
    description: "SSH public key to add to authorized_keys for debugging access"
    required: false
outputs:
  mtx:
    description: "A JSON array of objects for matrix strategies. Each object has: idx (overall 0-based index), id (runner label), instance_id, instance_idx (0-based instance index), runner_idx (0-based runner index within instance)"
  label:
    description: "The single runner label (for single instance use)"
  instance-id:
    description: "The EC2 instance ID (for single instance use)"
